export default {
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',

  WISHLIST_REQUEST: 'WISHLIST_REQUEST',
  CART_REQUEST: 'CART_REQUEST',
};
